spring:
  application:
    name: sb3-observability

management:
  endpoints:
    web:
      exposure:
        include: health
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
        step: 10s
---
spring:
  config:
    activate:
      on-profile: compose

---
spring:
  config:
    activate:
      on-profile: local

server:
  port: 8090

debug: true

logging:
  level:
    org.springframework.boot.actuate: trace
    org.springframework: trace
    io.micrometer.registry: trace
---
spring:
  config:
    activate:
      on-profile: homelab